apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: front-end
    app: redis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: redis
      labels:
        app: myapp
    spec:
      containers:
        - name: redis
          image: redis