apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_COLOR: blue
  APP_MODE: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  port: "3306"
  max_allowed_packet: 128M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  port: "6379"
  rdb-compression: "yes"
